package com.ssm.webservice.service.impl;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
import com.ssm.webservice.service.User;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390-
 * Generated source version: 2.0
 * 
 */
@WebService(name = "IMyService", targetNamespace = "http://service.webService.ssm.com/")
public interface IMyService {

	/**
	 * 
	 * @param arg0
	 * @return returns com.ssm.webservice.service.User
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "getUserById", targetNamespace = "http://service.webService.ssm.com/", className = "com.ssm.webservice.service.GetUserById")
	@ResponseWrapper(localName = "getUserByIdResponse", targetNamespace = "http://service.webService.ssm.com/", className = "com.ssm.webservice.service.GetUserByIdResponse")
	public User getUserById(
			@WebParam(name = "arg0", targetNamespace = "") long arg0);

	/**
	 * 
	 * @return returns java.util.List<com.ssm.webservice.service.User>
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "getAllUsers", targetNamespace = "http://service.webService.ssm.com/", className = "com.ssm.webservice.service.GetAllUsers")
	@ResponseWrapper(localName = "getAllUsersResponse", targetNamespace = "http://service.webService.ssm.com/", className = "com.ssm.webservice.service.GetAllUsersResponse")
	public List<User> getAllUsers();

}
