package com.ssm.webservice.service.impl;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390-
 * Generated source version: 2.0
 * <p>
 * An example of how this class may be used:
 * 
 * <pre>
 * MyServiceService service = new MyServiceService();
 * IMyService portType = service.getMyServicePort();
 * portType.getUserById(...);
 * </pre>
 * 
 * </p>
 * 
 */
@WebServiceClient(name = "MyServiceService", targetNamespace = "http://impl.service.webService.ssm.com/", wsdlLocation = "http://localhost:8888/xFire/service/userWS?wsdl")
public class MyServiceService extends Service {

	private final static URL MYSERVICESERVICE_WSDL_LOCATION;
	private final static Logger logger = Logger
			.getLogger(MyServiceService.class
					.getName());

	static {
		URL url = null;
		try {
			URL baseUrl;
			baseUrl = MyServiceService.class
					.getResource(".");
			url = new URL(baseUrl,
					"http://localhost:8888/xFire/service/userWS?wsdl");
		} catch (MalformedURLException e) {
			logger.warning("Failed to create URL for the wsdl Location: 'http://localhost:8888/xFire/service/userWS?wsdl', retrying as a local file");
			logger.warning(e.getMessage());
		}
		MYSERVICESERVICE_WSDL_LOCATION = url;
	}

	public MyServiceService(URL wsdlLocation, QName serviceName) {
		super(wsdlLocation, serviceName);
	}

	public MyServiceService() {
		super(MYSERVICESERVICE_WSDL_LOCATION, new QName(
				"http://impl.service.webService.ssm.com/", "MyServiceService"));
	}

	/**
	 * 
	 * @return returns IMyService
	 */
	@WebEndpoint(name = "MyServicePort")
	public IMyService getMyServicePort() {
		return super.getPort(new QName(
				"http://impl.service.webService.ssm.com/", "MyServicePort"),
				IMyService.class);
	}

}
